def on_overlap_tile(sprite, location):
    Lvlswitchercoinsetter()
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile19
    """),
    on_overlap_tile)

def on_up_pressed():
    if Godzilla.vy == 0:
        Godzilla.vy = -150
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_player2_button_b_pressed():
    global projectile
    animation.run_image_animation(Godzilla,
        [img("""
                ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555551ff555555bccc.....
                        c55d55ff55555555bc......
                        c5555555555555555b......
                        .cbb31bb5555dd555b.cc...
                        .c5333b555ddddd55dccc...
                        .c533b55ddddddddddb.....
                        .c5555dddbb55bdddddccc..
                        ..ccccbbbb555bdddddccc..
                        ...cdcbc5555bddddddcc...
                        ....ccbc55bc5ddddddbcccc
                        .....cbbcc5555dddddddddc
                        .....ccbbb555ddbddddddc.
                        .....cdcbc55ddbbbdddcc..
                        ...ccdddccddddbcbbcc....
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                ............ccc.........
                        .......cccccccc.........
                        .....cc55555cc..cc......
                        ....c555555555cccc......
                        ...c55555555555bcc......
                        ..c555551ff55555b..cc...
                        ..c55d55ff5555555bccc...
                        ..c55555555d55555bcc....
                        ..c5555d5555d55555b.....
                        ..cbbbb55555ddd555b.cc..
                        ..c555d5555ddddd55dccc..
                        ...c555dbbbdddbd5ddcc...
                        ....cccbbbbb555bdddb....
                        ....cbbbbbbc555bdddccc..
                        ...cbbbbbbc555bddddcc...
                        ...cbbbbbc555bdddddc....
                        ..ccbbbbbc55bddddddcc...
                        ..ccbbbbbbcb55dddddbcc..
                        ...cbbbbbb5555ddddddddcc
                        ....cbbbbb555ddbdddddddc
                        ....cccbbc55ddbbbddddcc.
                        ...ccdddccddddbcbbccc...
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                .............ccc........
                        ........cccccccc........
                        ......cc55555cc..cc.....
                        .....c555555555cccc.....
                        ....c55555555555bcc.....
                        ...c555555ccb5555b.cc...
                        ...c55d55c55555555bcc...
                        ...c55555555dd5555bc....
                        ...c5555d5555dd5555.....
                        ...cbbbd555555dd555.cc..
                        ...c555d555555ddd55ccc..
                        ....c555d5555ddbd5dcc...
                        ....cccbbbbb555bdddb....
                        ...cbbbbbbbc555bdddccc..
                        ..cbbbbbbbc555bddddcc...
                        ..cbbbbbbc555bdddddc....
                        .ccbbbbbbc55bddddddcc...
                        .ccbbbbbbbcb55dddddbc...
                        ..cbbbbbbb5555ddddddbc..
                        ...cbbbbbb555ddbddddddc.
                        ....cccbbc55ddbbbddddddc
                        ...ccdddccddddbcbbcccccc
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbbb5ddddd55dcc....
                        .c533bbbb5ddddddddbcc...
                        .c533bbb55dddddddddcccc.
                        .c5333bb5bb55bdddddcccdc
                        .c5333b5bb555bddddddbddc
                        .c53335b5555bddddddddddc
                        ..c5555c55bb55dbddddddcc
                        ...cccbccc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbbb5ddddd55dcc....
                        .c533bbbb5ddddddddbcc...
                        .c5333bb55dddddddddcccc.
                        .c5333b55bb55bdddddcccdc
                        .c533355bb555bddddddbddc
                        ..c5555b5555bddddddddddc
                        ...cccbc55bb55dbddddddcc
                        .....cbbcc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbb55ddddd55dcc....
                        .c5333bb5dddddddddbcc...
                        .c5333b55ddddddddddcccc.
                        .c533355dbb55bdddddcccdc
                        ..c55555bb555bddddddbddc
                        ...cccbb5555bddddddddddc
                        .....cbc55bb55dbddddddcc
                        .....cdbcc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """)],
        100,
        False)
    animation.run_image_animation(Godzilla,
        [img("""
            ........................
                    ........................
                    ..........ccc...........
                    .........cccc...........
                    .....ccccccc..ccc.......
                    ...cc555555cccccc.......
                    ..c5555555555bcc........
                    .c555555555555b..cc.....
                    c555551ff555555bccc.....
                    c55d55ff55555555bc......
                    c5555555555555555b......
                    .cbb31bb5555dd555b.cc...
                    .c5333b555ddddd55dccc...
                    .c533b55ddddddddddb.....
                    .c5555dddbb55bdddddccc..
                    ..ccccbbbb555bdddddccc..
                    ...cdcbc5555bddddddcc...
                    ....ccbc55bc5ddddddbcccc
                    .....cbbcc5555dddddddddc
                    .....ccbbb555ddbddddddc.
                    .....cdcbc55ddbbbdddcc..
                    ...ccdddccddddbcbbcc....
                    ...ccccccd555ddccc......
                    ........cccccccc........
        """)],
        100,
        False)
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        Godzilla,
        -50,
        0)
    pause(300)
controller.player2.on_button_event(ControllerButton.B,
    ControllerButtonEvent.PRESSED,
    on_player2_button_b_pressed)

def on_b_pressed():
    global projectile
    animation.run_image_animation(Godzilla,
        [img("""
                ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555551ff555555bccc.....
                        c55d55ff55555555bc......
                        c5555555555555555b......
                        .cbb31bb5555dd555b.cc...
                        .c5333b555ddddd55dccc...
                        .c533b55ddddddddddb.....
                        .c5555dddbb55bdddddccc..
                        ..ccccbbbb555bdddddccc..
                        ...cdcbc5555bddddddcc...
                        ....ccbc55bc5ddddddbcccc
                        .....cbbcc5555dddddddddc
                        .....ccbbb555ddbddddddc.
                        .....cdcbc55ddbbbdddcc..
                        ...ccdddccddddbcbbcc....
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                ............ccc.........
                        .......cccccccc.........
                        .....cc55555cc..cc......
                        ....c555555555cccc......
                        ...c55555555555bcc......
                        ..c555551ff55555b..cc...
                        ..c55d55ff5555555bccc...
                        ..c55555555d55555bcc....
                        ..c5555d5555d55555b.....
                        ..cbbbb55555ddd555b.cc..
                        ..c555d5555ddddd55dccc..
                        ...c555dbbbdddbd5ddcc...
                        ....cccbbbbb555bdddb....
                        ....cbbbbbbc555bdddccc..
                        ...cbbbbbbc555bddddcc...
                        ...cbbbbbc555bdddddc....
                        ..ccbbbbbc55bddddddcc...
                        ..ccbbbbbbcb55dddddbcc..
                        ...cbbbbbb5555ddddddddcc
                        ....cbbbbb555ddbdddddddc
                        ....cccbbc55ddbbbddddcc.
                        ...ccdddccddddbcbbccc...
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                .............ccc........
                        ........cccccccc........
                        ......cc55555cc..cc.....
                        .....c555555555cccc.....
                        ....c55555555555bcc.....
                        ...c555555ccb5555b.cc...
                        ...c55d55c55555555bcc...
                        ...c55555555dd5555bc....
                        ...c5555d5555dd5555.....
                        ...cbbbd555555dd555.cc..
                        ...c555d555555ddd55ccc..
                        ....c555d5555ddbd5dcc...
                        ....cccbbbbb555bdddb....
                        ...cbbbbbbbc555bdddccc..
                        ..cbbbbbbbc555bddddcc...
                        ..cbbbbbbc555bdddddc....
                        .ccbbbbbbc55bddddddcc...
                        .ccbbbbbbbcb55dddddbc...
                        ..cbbbbbbb5555ddddddbc..
                        ...cbbbbbb555ddbddddddc.
                        ....cccbbc55ddbbbddddddc
                        ...ccdddccddddbcbbcccccc
                        ...ccccccd555ddccc......
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbbb5ddddd55dcc....
                        .c533bbbb5ddddddddbcc...
                        .c533bbb55dddddddddcccc.
                        .c5333bb5bb55bdddddcccdc
                        .c5333b5bb555bddddddbddc
                        .c53335b5555bddddddddddc
                        ..c5555c55bb55dbddddddcc
                        ...cccbccc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbbb5ddddd55dcc....
                        .c533bbbb5ddddddddbcc...
                        .c5333bb55dddddddddcccc.
                        .c5333b55bb55bdddddcccdc
                        .c533355bb555bddddddbddc
                        ..c5555b5555bddddddddddc
                        ...cccbc55bb55dbddddddcc
                        .....cbbcc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ccc...........
                        .........cccc...........
                        .....ccccccc..ccc.......
                        ...cc555555cccccc.......
                        ..c5555555555bcc........
                        .c555555555555b..cc.....
                        c555555ccb55555bccc.....
                        c55d55c555555555bc......
                        c5555555555555555b......
                        .cbbb1bb5555dd555b.cc...
                        .c533bbb55ddddd55dcc....
                        .c5333bb5dddddddddbcc...
                        .c5333b55ddddddddddcccc.
                        .c533355dbb55bdddddcccdc
                        ..c55555bb555bddddddbddc
                        ...cccbb5555bddddddddddc
                        .....cbc55bb55dbddddddcc
                        .....cdbcc55ddbbbddddcc.
                        ....cdddccddddbcbbbcc...
                        ....cccccd555ddcccc.....
                        ........cccccccc........
            """)],
        100,
        False)
    animation.run_image_animation(Godzilla,
        [img("""
            ........................
                    ........................
                    ..........ccc...........
                    .........cccc...........
                    .....ccccccc..ccc.......
                    ...cc555555cccccc.......
                    ..c5555555555bcc........
                    .c555555555555b..cc.....
                    c555551ff555555bccc.....
                    c55d55ff55555555bc......
                    c5555555555555555b......
                    .cbb31bb5555dd555b.cc...
                    .c5333b555ddddd55dccc...
                    .c533b55ddddddddddb.....
                    .c5555dddbb55bdddddccc..
                    ..ccccbbbb555bdddddccc..
                    ...cdcbc5555bddddddcc...
                    ....ccbc55bc5ddddddbcccc
                    .....cbbcc5555dddddddddc
                    .....ccbbb555ddbddddddc.
                    .....cdcbc55ddbbbdddcc..
                    ...ccdddccddddbcbbcc....
                    ...ccccccd555ddccc......
                    ........cccccccc........
        """)],
        100,
        False)
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        Godzilla,
        -50,
        0)
    pause(300)
controller.B.on_event(ControllerButtonEvent.PRESSED, on_b_pressed)

def on_a_pressed():
    global projectile
    animation.run_image_animation(Godzilla,
        [img("""
                ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb555555ff155555c
                        ......cb55555555ff55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb13bbc.
                        ...cccd55ddddd555b3335c.
                        .....bdddddddddd55b335c.
                        ..cccdddddb55bbddd5555c.
                        ..cccdddddb555bbbbcccc..
                        ...ccddddddb5555cbcdc...
                        ccccbdddddd5cb55cbcc....
                        cddddddddd5555ccbbc.....
                        .cddddddbdd555bbbcc.....
                        ..ccdddbbbdd55cbcdc.....
                        ....ccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                .........ccc............
                        .........cccccccc.......
                        ......cc..cc55555cc.....
                        ......cccc555555555c....
                        ......ccb55555555555c...
                        ...cc..b55555ff155555c..
                        ...cccb5555555ff55d55c..
                        ....ccb55555d55555555c..
                        .....b55555d5555d5555c..
                        ..cc.b555ddd55555bbbbc..
                        ..cccd55ddddd5555d555c..
                        ...ccdd5dbdddbbbd555c...
                        ....bdddb555bbbbbccc....
                        ..cccdddb555cbbbbbbc....
                        ...ccddddb555cbbbbbbc...
                        ....cdddddb555cbbbbbc...
                        ...ccddddddb55cbbbbbcc..
                        ..ccbddddd55bcbbbbbbcc..
                        ccdddddddd5555bbbbbbc...
                        cdddddddbdd555bbbbbc....
                        .ccddddbbbdd55cbbccc....
                        ...cccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                ........ccc.............
                        ........cccccccc........
                        .....cc..cc55555cc......
                        .....cccc555555555c.....
                        .....ccb55555555555c....
                        ...cc.b5555bcc555555c...
                        ...ccb55555555c55d55c...
                        ....cb5555dd55555555c...
                        .....5555dd5555d5555c...
                        ..cc.555dd555555dbbbc...
                        ..ccc55ddd555555d555c...
                        ...ccd5dbdd5555d555c....
                        ....bdddb555bbbbbccc....
                        ..cccdddb555cbbbbbbbc...
                        ...ccddddb555cbbbbbbbc..
                        ....cdddddb555cbbbbbbc..
                        ...ccddddddb55cbbbbbbcc.
                        ...cbddddd55bcbbbbbbbcc.
                        ..cbdddddd5555bbbbbbbc..
                        .cddddddbdd555bbbbbbc...
                        cddddddbbbdd55cbbccc....
                        ccccccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd5bbbb335c.
                        ...ccbdddddddd5bbbb335c.
                        .ccccddddddddd55bbb335c.
                        cdcccdddddb55bb5bb3335c.
                        cddbddddddb555bb5b3335c.
                        cddddddddddb5555b53335c.
                        ccddddddbd55bb55c5555c..
                        .ccddddbbbdd55cccbccc...
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd5bbbb335c.
                        ...ccbdddddddd5bbbb335c.
                        .ccccddddddddd55bb3335c.
                        cdcccdddddb55bb55b3335c.
                        cddbddddddb555bb553335c.
                        cddddddddddb5555b5555c..
                        ccddddddbd55bb55cbccc...
                        .ccddddbbbdd55ccbbc.....
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd55bbb335c.
                        ...ccbddddddddd5bb3335c.
                        .ccccdddddddddd55b3335c.
                        cdcccdddddb55bbd553335c.
                        cddbddddddb555bb55555c..
                        cddddddddddb5555bbccc...
                        ccddddddbd55bb55cbc.....
                        .ccddddbbbdd55ccbdc.....
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """)],
        500,
        False)
    animation.run_image_animation(Godzilla,
        [img("""
            ........................
                    ........................
                    ...........ccc..........
                    ...........cccc.........
                    .......ccc..ccccccc.....
                    .......cccccc555555cc...
                    ........ccb5555555555c..
                    .....cc..b555555555555c.
                    .....cccb555555ff155555c
                    ......cb55555555ff55d55c
                    ......b5555555555555555c
                    ...cc.b555dd5555bb13bbc.
                    ...cccd55ddddd555b3335c.
                    .....bdddddddddd55b335c.
                    ..cccdddddb55bbddd5555c.
                    ..cccdddddb555bbbbcccc..
                    ...ccddddddb5555cbcdc...
                    ccccbdddddd5cb55cbcc....
                    cddddddddd5555ccbbc.....
                    .cddddddbdd555bbbcc.....
                    ..ccdddbbbdd55cbcdc.....
                    ....ccbbcbddddccdddcc...
                    ......cccdd555dcccccc...
                    ........cccccccc........
        """)],
        100,
        False)
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        Godzilla,
        50,
        16)
    pause(300)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_player2_button_a_pressed():
    global projectile
    animation.run_image_animation(Godzilla,
        [img("""
                ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb555555ff155555c
                        ......cb55555555ff55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb13bbc.
                        ...cccd55ddddd555b3335c.
                        .....bdddddddddd55b335c.
                        ..cccdddddb55bbddd5555c.
                        ..cccdddddb555bbbbcccc..
                        ...ccddddddb5555cbcdc...
                        ccccbdddddd5cb55cbcc....
                        cddddddddd5555ccbbc.....
                        .cddddddbdd555bbbcc.....
                        ..ccdddbbbdd55cbcdc.....
                        ....ccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                .........ccc............
                        .........cccccccc.......
                        ......cc..cc55555cc.....
                        ......cccc555555555c....
                        ......ccb55555555555c...
                        ...cc..b55555ff155555c..
                        ...cccb5555555ff55d55c..
                        ....ccb55555d55555555c..
                        .....b55555d5555d5555c..
                        ..cc.b555ddd55555bbbbc..
                        ..cccd55ddddd5555d555c..
                        ...ccdd5dbdddbbbd555c...
                        ....bdddb555bbbbbccc....
                        ..cccdddb555cbbbbbbc....
                        ...ccddddb555cbbbbbbc...
                        ....cdddddb555cbbbbbc...
                        ...ccddddddb55cbbbbbcc..
                        ..ccbddddd55bcbbbbbbcc..
                        ccdddddddd5555bbbbbbc...
                        cdddddddbdd555bbbbbc....
                        .ccddddbbbdd55cbbccc....
                        ...cccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                ........ccc.............
                        ........cccccccc........
                        .....cc..cc55555cc......
                        .....cccc555555555c.....
                        .....ccb55555555555c....
                        ...cc.b5555bcc555555c...
                        ...ccb55555555c55d55c...
                        ....cb5555dd55555555c...
                        .....5555dd5555d5555c...
                        ..cc.555dd555555dbbbc...
                        ..ccc55ddd555555d555c...
                        ...ccd5dbdd5555d555c....
                        ....bdddb555bbbbbccc....
                        ..cccdddb555cbbbbbbbc...
                        ...ccddddb555cbbbbbbbc..
                        ....cdddddb555cbbbbbbc..
                        ...ccddddddb55cbbbbbbcc.
                        ...cbddddd55bcbbbbbbbcc.
                        ..cbdddddd5555bbbbbbbc..
                        .cddddddbdd555bbbbbbc...
                        cddddddbbbdd55cbbccc....
                        ccccccbbcbddddccdddcc...
                        ......cccdd555dcccccc...
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd5bbbb335c.
                        ...ccbdddddddd5bbbb335c.
                        .ccccddddddddd55bbb335c.
                        cdcccdddddb55bb5bb3335c.
                        cddbddddddb555bb5b3335c.
                        cddddddddddb5555b53335c.
                        ccddddddbd55bb55c5555c..
                        .ccddddbbbdd55cccbccc...
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd5bbbb335c.
                        ...ccbdddddddd5bbbb335c.
                        .ccccddddddddd55bb3335c.
                        cdcccdddddb55bb55b3335c.
                        cddbddddddb555bb553335c.
                        cddddddddddb5555b5555c..
                        ccddddddbd55bb55cbccc...
                        .ccddddbbbdd55ccbbc.....
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........ccc..........
                        ...........cccc.........
                        .......ccc..ccccccc.....
                        .......cccccc555555cc...
                        ........ccb5555555555c..
                        .....cc..b555555555555c.
                        .....cccb55555bcc555555c
                        ......cb555555555c55d55c
                        ......b5555555555555555c
                        ...cc.b555dd5555bb1bbbc.
                        ....ccd55ddddd55bbb335c.
                        ...ccbddddddddd5bb3335c.
                        .ccccdddddddddd55b3335c.
                        cdcccdddddb55bbd553335c.
                        cddbddddddb555bb55555c..
                        cddddddddddb5555bbccc...
                        ccddddddbd55bb55cbc.....
                        .ccddddbbbdd55ccbdc.....
                        ...ccbbbcbddddccdddc....
                        .....ccccdd555dccccc....
                        ........cccccccc........
            """)],
        500,
        False)
    animation.run_image_animation(Godzilla,
        [img("""
            ........................
                    ........................
                    ...........ccc..........
                    ...........cccc.........
                    .......ccc..ccccccc.....
                    .......cccccc555555cc...
                    ........ccb5555555555c..
                    .....cc..b555555555555c.
                    .....cccb555555ff155555c
                    ......cb55555555ff55d55c
                    ......b5555555555555555c
                    ...cc.b555dd5555bb13bbc.
                    ...cccd55ddddd555b3335c.
                    .....bdddddddddd55b335c.
                    ..cccdddddb55bbddd5555c.
                    ..cccdddddb555bbbbcccc..
                    ...ccddddddb5555cbcdc...
                    ccccbdddddd5cb55cbcc....
                    cddddddddd5555ccbbc.....
                    .cddddddbdd555bbbcc.....
                    ..ccdddbbbdd55cbcdc.....
                    ....ccbbcbddddccdddcc...
                    ......cccdd555dcccccc...
                    ........cccccccc........
        """)],
        100,
        False)
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 5 5 . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        Godzilla,
        50,
        16)
    pause(300)
controller.player2.on_button_event(ControllerButton.A,
    ControllerButtonEvent.PRESSED,
    on_player2_button_a_pressed)

def Lvlswitchercoinsetter():
    global Coin
    Godzilla.ay = 0
    sprites.destroy_all_sprites_of_kind(SpriteKind.enemy, effects.spray, 500)
    Godzilla.set_stay_in_screen(True)
    tiles.set_current_tilemap(tilemap("""
        level22
    """))
    tiles.place_on_random_tile(Godzilla, assets.tile("""
        myTile23
    """))
    tiles.place_on_random_tile(Godzilla_2, assets.tile("""
        myTile23
    """))
    Godzilla.ay = 100
    pause(1000)
    Godzilla.ay = 300
    for index in range(150):
        Coin = sprites.create(img("""
                . . b b b b . . 
                            . b 5 5 5 5 b . 
                            b 5 d 3 3 d 5 b 
                            b 5 3 5 5 1 5 b 
                            c 5 3 5 5 1 d c 
                            c d d 1 1 d d c 
                            . f d d d d f . 
                            . . f f f f . .
            """),
            SpriteKind.food)
        tiles.place_on_random_tile(Coin, assets.tile("""
            myTile25
        """))
        animation.run_image_animation(Coin,
            [img("""
                    . . b b b b . . 
                                . b 5 5 5 5 b . 
                                b 5 d 3 3 d 5 b 
                                b 5 3 5 5 1 5 b 
                                c 5 3 5 5 1 d c 
                                c d d 1 1 d d c 
                                . f d d d d f . 
                                . . f f f f . .
                """),
                img("""
                    . . b b b . . . 
                                . b 5 5 5 b . . 
                                b 5 d 3 d 5 b . 
                                b 5 3 5 1 5 b . 
                                c 5 3 5 1 d c . 
                                c 5 d 1 d d c . 
                                . f d d d f . . 
                                . . f f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . b 5 d 1 5 b . 
                                . b 5 3 1 5 b . 
                                . c 5 3 1 d c . 
                                . c 5 1 d d c . 
                                . . f d d f . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . . b 1 1 b . . 
                                . . b 5 5 b . . 
                                . . b d d b . . 
                                . . c d d c . . 
                                . . c 3 3 c . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . b 5 1 d 5 b . 
                                . b 5 1 3 5 b . 
                                . c d 1 3 5 c . 
                                . c d d 1 5 c . 
                                . . f d d f . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b b . . 
                                . . b 5 5 5 b . 
                                . b 5 d 3 d 5 b 
                                . b 5 1 5 3 5 b 
                                . c d 1 5 3 5 c 
                                . c d d 1 d 5 c 
                                . . f d d d f . 
                                . . . f f f . .
                """)],
            100,
            True)

def on_player2_button_up_pressed():
    if Godzilla_2.vy == 0:
        Godzilla_2.vy = -150
controller.player2.on_button_event(ControllerButton.UP,
    ControllerButtonEvent.PRESSED,
    on_player2_button_up_pressed)

def What_to_do_on_start():
    global Point, textSprite, Godzilla, Godzilla_2, mushroom, Coin
    Point = 0
    textSprite = textsprite.create("0")
    tiles.set_current_tilemap(tilemap("""
        level1
    """))
    Godzilla = sprites.create(img("""
            ........................
                    ........................
                    ...........ccc..........
                    ...........cccc.........
                    .......ccc..ccccccc.....
                    .......cccccc555555cc...
                    ........ccb5555555555c..
                    .....cc..b555555555555c.
                    .....cccb555555ff155555c
                    ......cb55555555ff55d55c
                    ......b5555555555555555c
                    ...cc.b555dd5555bb13bbc.
                    ...cccd55ddddd555b3335c.
                    .....bdddddddddd55b335c.
                    ..cccdddddb55bbddd5555c.
                    ..cccdddddb555bbbbcccc..
                    ...ccddddddb5555cbcdc...
                    ccccbdddddd5cb55cbcc....
                    cddddddddd5555ccbbc.....
                    .cddddddbdd555bbbcc.....
                    ..ccdddbbbdd55cbcdc.....
                    ....ccbbcbddddccdddcc...
                    ......cccdd555dcccccc...
                    ........cccccccc........
        """),
        SpriteKind.player)
    Godzilla_2 = sprites.create(img("""
            . . . . b b b b . . . . . . . . 
                    . . . b 3 3 3 3 b b b b . . . . 
                    . . b b 3 3 3 3 3 1 1 b b c c . 
                    . . b 1 1 3 3 3 3 3 1 1 3 b c c 
                    . . b 1 1 3 3 3 3 3 3 3 3 3 b c 
                    . . c 3 3 3 3 3 b c c c c b b f 
                    . c 3 3 3 3 b b d d d c c c b f 
                    c b 3 3 b b d d d d d d b c b f 
                    c 3 3 c b d d d d d d c d b c . 
                    f 3 c c c d d c d d d c d d c . 
                    f b c c c d d d c d d d d d f . 
                    f b c c c f f b d d b b b d f . 
                    f f b b f b d d b d d d d c . . 
                    . f f f f d d b b d d d c . . . 
                    . . . . b b b b f b b f f . . . 
                    . . . . . . . f f b b b f . . .
        """),
        SpriteKind.player)
    Godzilla.set_scale(0.5, ScaleAnchor.MIDDLE)
    Godzilla_2.set_scale(1, ScaleAnchor.MIDDLE)
    controller.move_sprite(Godzilla, 100, 0)
    controller.player2.move_sprite(Godzilla_2, 100, 0)
    Godzilla.ay = 300
    Godzilla_2.ay = 300
    tiles.place_on_random_tile(Godzilla, assets.tile("""
        myTile15
    """))
    tiles.place_on_random_tile(Godzilla_2, assets.tile("""
        myTile15
    """))
    scene.camera_follow_sprite(Godzilla)
    for index2 in range(20):
        mushroom = sprites.create(img("""
                . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . 1 1 2 1 1 1 . . . . . . 
                            . . . 1 2 1 1 1 2 1 1 . . . . . 
                            . . . 1 1 e e e e 1 2 . . . . . 
                            . . . 2 e f e e f e 1 . . . . . 
                            . . . . e e e e e e . . . . . . 
                            . . . . . e e e e . . . . . . . 
                            . . . . . e . . e . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . . 
                            . . . . . . . . . . . . . . . .
            """),
            SpriteKind.enemy)
        mushroom.set_scale(2, ScaleAnchor.MIDDLE)
        tiles.place_on_random_tile(mushroom, assets.tile("""
            myTile18
        """))
        mushroom.set_velocity(50, 0)
        mushroom.set_bounce_on_wall(True)
        Coin = sprites.create(img("""
                . . b b b b . . 
                            . b 5 5 5 5 b . 
                            b 5 d 3 3 d 5 b 
                            b 5 3 5 5 1 5 b 
                            c 5 3 5 5 1 d c 
                            c d d 1 1 d d c 
                            . f d d d d f . 
                            . . f f f f . .
            """),
            SpriteKind.food)
        tiles.place_on_random_tile(Coin, assets.tile("""
            myTile11
        """))
        animation.run_image_animation(Coin,
            [img("""
                    . . b b b b . . 
                                . b 5 5 5 5 b . 
                                b 5 d 3 3 d 5 b 
                                b 5 3 5 5 1 5 b 
                                c 5 3 5 5 1 d c 
                                c d d 1 1 d d c 
                                . f d d d d f . 
                                . . f f f f . .
                """),
                img("""
                    . . b b b . . . 
                                . b 5 5 5 b . . 
                                b 5 d 3 d 5 b . 
                                b 5 3 5 1 5 b . 
                                c 5 3 5 1 d c . 
                                c 5 d 1 d d c . 
                                . f d d d f . . 
                                . . f f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . b 5 d 1 5 b . 
                                . b 5 3 1 5 b . 
                                . c 5 3 1 d c . 
                                . c 5 1 d d c . 
                                . . f d d f . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . . b 1 1 b . . 
                                . . b 5 5 b . . 
                                . . b d d b . . 
                                . . c d d c . . 
                                . . c 3 3 c . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b . . . 
                                . . b 5 5 b . . 
                                . b 5 1 d 5 b . 
                                . b 5 1 3 5 b . 
                                . c d 1 3 5 c . 
                                . c d d 1 5 c . 
                                . . f d d f . . 
                                . . . f f . . .
                """),
                img("""
                    . . . b b b . . 
                                . . b 5 5 5 b . 
                                . b 5 d 3 d 5 b 
                                . b 5 1 5 3 5 b 
                                . c d 1 5 3 5 c 
                                . c d d 1 d 5 c 
                                . . f d d d f . 
                                . . . f f f . .
                """)],
            500,
            True)

def on_on_overlap(sprite2, otherSprite):
    global Point
    music.ba_ding.play()
    Point += 1
    otherSprite.destroy()
sprites.on_overlap(SpriteKind.player, SpriteKind.food, on_on_overlap)

def on_overlap_tile2(sprite3, location2):
    game.over(False, effects.splatter)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile10
    """),
    on_overlap_tile2)

def on_overlap_tile3(sprite4, location3):
    game.over(True, effects.smiles)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile27
    """),
    on_overlap_tile3)

def on_on_overlap2(sprite5, otherSprite2):
    otherSprite2.destroy()
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap2)

def on_overlap_tile4(sprite6, location4):
    game.over(False, effects.splatter)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        myTile26
    """),
    on_overlap_tile4)

def on_on_overlap3(sprite7, otherSprite3):
    game.over(False, effects.blizzard)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap3)

mushroom: Sprite = None
textSprite: TextSprite = None
Point = 0
Coin: Sprite = None
projectile: Sprite = None
Godzilla: Sprite = None
Godzilla_2: Sprite = None
What_to_do_on_start()
animation.run_image_animation(Godzilla_2,
    [img("""
            . . . . b b b b . . . . . . . . 
                . . . b 3 3 3 3 b b b b . . . . 
                . . b b 3 3 3 3 3 1 1 b b c c . 
                . . b 1 1 3 3 3 3 3 1 1 3 b c c 
                . . b 1 1 3 3 3 3 3 3 3 3 3 b c 
                . . c 3 3 3 3 3 b c c c c b b f 
                . c 3 3 3 3 b b d d d c c c b f 
                c b 3 3 b b d d d d d d b c b f 
                c 3 3 c b d d d d d d c d b c . 
                f 3 c c c d d c d d d c d d c . 
                f b c c c d d d c d d d d d f . 
                f b c c c f f b d d b b b d f . 
                f f b b f b d d b d d d d c . . 
                . f f f f d d b b d d d c . . . 
                . . . . b b b b f b b f f . . . 
                . . . . . . . f f b b b f . . .
        """),
        img("""
            . . . . . . . . . . . . . . . . 
                . . . . b b b b . . . . . . . . 
                . . . b 3 3 3 3 b b b b . . . . 
                . . b b 3 3 3 3 3 1 1 b b c c . 
                . . b 1 1 3 3 3 3 1 1 1 3 c c c 
                . . b 1 1 3 3 3 3 3 3 3 3 3 b c 
                . . c 1 1 3 3 b b c c c c b b f 
                . c c 3 3 b b d d d d b c c b f 
                c b 3 3 b b d d d d d d d c b f 
                c 3 3 b b d d d d d d c d d c . 
                f 3 3 c b d d c d d d c d d c . 
                f b c c c d d d c d d d d d f . 
                f b c c c d d f f b b b b d f . 
                f f b b c c f b d d b d d c . . 
                . f f f c c f d d b b d c . . . 
                . . . . . . b b b b f c . . . .
        """),
        img("""
            . . . . . . . . . . . . . . . . 
                . . . . b b b b . . . . . . . . 
                . . . b 3 3 3 3 b b b b . . . . 
                . . b b 3 3 3 3 3 3 1 1 b c c . 
                . . b 3 3 3 3 3 3 1 1 1 3 c c c 
                . . b 1 1 3 3 3 3 3 3 3 3 3 b c 
                . . c 1 1 3 3 3 b c c c c b b f 
                . c c 3 3 3 b b d d d c c c b f 
                c b 3 3 b b d d d d d d b c b f 
                c 3 3 c b d d d d d d d d b c . 
                f 3 c c c d d d d d d c c d c . 
                f b c c c d d c c d d d d d f . 
                f b c c c d d d d d b b b d f . 
                f f b b c f f b d d d d d c . . 
                . f f f f d d b b d d d b f . . 
                . . . . f d d d b c c f f f . .
        """),
        img("""
            . . . . b b b b . . . . . . . . 
                . . . b 3 3 3 3 b b b b . . . . 
                . . b b 3 3 3 3 3 1 1 b b c c . 
                . . b 1 1 3 3 3 3 3 1 1 3 3 c c 
                . . b 1 1 3 3 3 3 3 3 3 3 3 b c 
                . . c 3 3 3 3 3 3 3 c c c b b f 
                . c 3 3 3 3 3 b b b b c c c b f 
                c 3 3 3 3 b b d d d d d c c b f 
                c 3 3 c b d d d d d d c d c c . 
                f 3 c c c d d c d d d c d b c . 
                f b c c c d d d c d d d d d f . 
                f b c c c d d d d d b b b d f . 
                f f b b c b d d d d d d d c . . 
                . f f f f b c c d d d d f f . . 
                . . f b d d b c c f f b b f f . 
                . . f d d d b . . f f b b b f .
        """)],
    100,
    False)

def on_forever():
    textSprite.set_text(convert_to_text(Point))
    textSprite.set_position(scene.camera_property(CameraProperty.X) + 20,
        scene.camera_property(CameraProperty.Y) + 20)
forever(on_forever)

def on_forever2():
    if controller.left.is_pressed():
        animation.run_image_animation(Godzilla,
            [img("""
                    ........................
                                ........................
                                ...........cc...........
                                .........cccc...........
                                .....ccccccc...cc.......
                                ...cc555555cccccc.......
                                ..c5555555555bcc........
                                .c555555555555b..cc.....
                                c555551ff555555bccc.....
                                c55d55ff55555555bcc.....
                                c5555555555555555b......
                                .cbb31bb55555d555b..c...
                                .c5333bb55ddddd55dccc...
                                .c533b55ddddddddddbc....
                                .c5555ddddb55bdddddccc..
                                ..ccccbbbb555bdddddccc..
                                ...cdcbc5555bddddddcc...
                                ....ccbc55bcdddddddbcccc
                                .....cbbccbd55dddddddddc
                                .....ccbbbd555ddddddddbc
                                ...ccbdcbb555ddbbdddbcc.
                                ...cbdddcc55ddbbbbccc...
                                ...cccccccbdddbccc......
                                ........cd555ddc........
                """),
                img("""
                    ........................
                                ........................
                                ..........ccc...........
                                .........cccc...........
                                .....ccccccc..ccc.......
                                ...cc555555cccccc.......
                                ..c5555555555bcc........
                                .c555555555555b..cc.....
                                c555551ff555555bccc.....
                                c55d55ff55555555bc......
                                c5555555555555555b......
                                .cbb31bb5555dd555b.cc...
                                .c5333b555ddddd55dccc...
                                .c533b55ddddddddddb.....
                                .c5555dddbb55bdddddccc..
                                ..ccccbbbb555bdddddccc..
                                ...cdcbc5555bddddddcc...
                                ....ccbc55bc5ddddddbcccc
                                .....cbbcc5555dddddddddc
                                .....ccbbb555ddbddddddc.
                                .....cdcbc55ddbbbdddcc..
                                ...ccdddccddddbcbbcc....
                                ...ccccccd555ddccc......
                                ........cccccccc........
                """),
                img("""
                    ........................
                                ..........cc............
                                .........ccc............
                                .....ccccccc.ccc........
                                ...cc555555ccccc........
                                ..c5555555555bcc........
                                .c55551ff55555b.ccc.....
                                c55555ff5555555bccc.....
                                c55d555555555555bc......
                                c55555bb555555555b.c....
                                .cbb31b5555ddd555bcc....
                                .c5333b555ddddd55dcc....
                                .c533b55ddddddd5ddc.....
                                ..c555dbbb555bddddb.c...
                                ...cccb55555bbdddddcc...
                                ....ccb555ccdddddddcc...
                                ..ccccbcccbddddddddcc...
                                ..c55cbbbbd55dddddddbcc.
                                ...c5ccbbd555dddddddddcc
                                ....cccbb555ddbbbddddddc
                                ......ccb55ddbbbbddddcc.
                                ....ccddcbdddbbbbbccc...
                                ....ccccd555ddccccc.....
                                ........cccccc..........
                """),
                img("""
                    ........................
                                ..........cc............
                                .........ccc............
                                .....ccccccc.ccc........
                                ...cc555555ccccc........
                                ..c5555555555bcc........
                                .c55551ff55555b.ccc.....
                                c55555ff5555555bccc.....
                                c55d555555555555bc......
                                c55555bb555555555b.c....
                                .cbb31b5555ddd555bcc....
                                .c5333b555ddddd55dcc....
                                .c533b55ddddddd5ddc.....
                                ..c555dbbb555bddddb.c...
                                ...cccb55555bbdddddcc...
                                ....ccb555ccdddddddcc...
                                ..ccccbcccdddddddddcccc.
                                ..c55cbbbd55ddddddddcdc.
                                ...c5cccd555ddddddddddc.
                                ....cc555d5ddbbbbddddbc.
                                ......5555ddbbbbbdddbc..
                                ......c5555dbbbbbbccc...
                                .......c555cccccccc.....
                                ........ccc.............
                """),
                img("""
                    ........................
                                ..........cc............
                                .........ccc............
                                .....ccccccc.ccc........
                                ...cc555555ccccc........
                                ..c5555555555bcc........
                                .c55551ff55555b.ccc.....
                                c55555ff5555555bccc.....
                                c55d555555555555bc......
                                c55555bb555555555b.c....
                                .cbb31b5555ddd555bcc....
                                .c5333b555ddddd55dcc....
                                .c533b55ddddddd5ddc.....
                                ..c555dbbb555bddddb.c...
                                ...cccb555555bdddddcc...
                                ....ccb5555ccddddddccc..
                                ..ccccbcccbddddddddccdc.
                                ..c55cbbbbdddddddddbddc.
                                ...c5cbbbd55ddddddddddc.
                                ....cccbdd55dbbbbddddbc.
                                .....cccd555dbbbbdddbc..
                                .....c555dddbbbbbbccc...
                                .....c55555dbcccccc.....
                                ......c5555cc...........
                """),
                img("""
                    ........................
                                ..........cc............
                                .........ccc............
                                .....ccccccc..cc........
                                ...cc555555ccccc........
                                ..c5555555555bcc........
                                .c555555555555b..cc.....
                                c555551ff555555bccc.....
                                c55d55ff55555555bc......
                                c5555555555555555b......
                                .cbb31bb5555dd555b.cc...
                                .c5333b555ddddd55dccc...
                                .c533b55ddddddd5ddcc....
                                .c5555ddddb55bddddb.....
                                ..ccccbbbbb55bdddddccc..
                                ..ccccbc5555bddddddcccc.
                                ..c55cbc555cdddddddccdc.
                                ...c5cbbcccdddddddddddc.
                                ....cccbbbbd55dddddddbc.
                                ....cbcbbbd555ddddddbcc.
                                .....cccbb555dbbbddccc..
                                .......cc555dbbbbbcc....
                                .......cbddddbcccc......
                                ......cd5555dc..........
                """)],
            500,
            False)
forever(on_forever2)

def on_forever3():
    if controller.right.is_pressed():
        animation.run_image_animation(Godzilla,
            [img("""
                    ........................
                                ........................
                                ...........cc...........
                                ...........cccc.........
                                .......cc...ccccccc.....
                                .......cccccc555555cc...
                                ........ccb5555555555c..
                                .....cc..b555555555555c.
                                .....cccb555555ff155555c
                                .....ccb55555555ff55d55c
                                ......b5555555555555555c
                                ...c..b555d55555bb13bbc.
                                ...cccd55ddddd55bb3335c.
                                ....cbdddddddddd55b335c.
                                ..cccdddddb55bdddd5555c.
                                ..cccdddddb555bbbbcccc..
                                ...ccddddddb5555cbcdc...
                                ccccbdddddddcb55cbcc....
                                cddddddddd55dbccbbc.....
                                cbdddddddd555dbbbcc.....
                                .ccbdddbbdd555bbcdbcc...
                                ...cccbbbbdd55ccdddbc...
                                ......cccbdddbccccccc...
                                ........cdd555dc........
                """),
                img("""
                    ........................
                                ........................
                                ...........ccc..........
                                ...........cccc.........
                                .......ccc..ccccccc.....
                                .......cccccc555555cc...
                                ........ccb5555555555c..
                                .....cc..b555555555555c.
                                .....cccb555555ff155555c
                                ......cb55555555ff55d55c
                                ......b5555555555555555c
                                ...cc.b555dd5555bb13bbc.
                                ...cccd55ddddd555b3335c.
                                .....bdddddddddd55b335c.
                                ..cccdddddb55bbddd5555c.
                                ..cccdddddb555bbbbcccc..
                                ...ccddddddb5555cbcdc...
                                ccccbdddddd5cb55cbcc....
                                cddddddddd5555ccbbc.....
                                .cddddddbdd555bbbcc.....
                                ..ccdddbbbdd55cbcdc.....
                                ....ccbbcbddddccdddcc...
                                ......cccdd555dcccccc...
                                ........cccccccc........
                """),
                img("""
                    ........................
                                ............cc..........
                                ............ccc.........
                                ........ccc.ccccccc.....
                                ........ccccc555555cc...
                                ........ccb5555555555c..
                                .....ccc.b55555ff15555c.
                                .....cccb5555555ff55555c
                                ......cb555555555555d55c
                                ....c.b555555555bb55555c
                                ....ccb555ddd5555b13bbc.
                                ....ccd55ddddd555b3335c.
                                .....cdd5ddddddd55b335c.
                                ...c.bddddb555bbbd555c..
                                ...ccdddddbb55555bccc...
                                ...ccdddddddcc555bcc....
                                ...ccddddddddbcccbcccc..
                                .ccbddddddd55dbbbbc55c..
                                ccddddddddd555dbbcc5c...
                                cddddddbbbdd555bbccc....
                                .ccddddbbbbdd55bcc......
                                ...cccbbbbbdddbcddcc....
                                .....cccccdd555dcccc....
                                ..........cccccc........
                """),
                img("""
                    ........................
                                ............cc..........
                                ............ccc.........
                                ........ccc.ccccccc.....
                                ........ccccc555555cc...
                                ........ccb5555555555c..
                                .....ccc.b55555ff15555c.
                                .....cccb5555555ff55555c
                                ......cb555555555555d55c
                                ....c.b555555555bb55555c
                                ....ccb555ddd5555b13bbc.
                                ....ccd55ddddd555b3335c.
                                .....cdd5ddddddd55b335c.
                                ...c.bddddb555bbbd555c..
                                ...ccdddddbb55555bccc...
                                ...ccdddddddcc555bcc....
                                .ccccdddddddddcccbcccc..
                                .cdcdddddddd55dbbbc55c..
                                .cdddddddddd555dccc5c...
                                .cbddddbbbbdd5d555cc....
                                ..cbdddbbbbbdd5555......
                                ...cccbbbbbbd5555c......
                                .....cccccccc555c.......
                                .............ccc........
                """),
                img("""
                    ........................
                                ............cc..........
                                ............ccc.........
                                ........ccc.ccccccc.....
                                ........ccccc555555cc...
                                ........ccb5555555555c..
                                .....ccc.b55555ff15555c.
                                .....cccb5555555ff55555c
                                ......cb555555555555d55c
                                ....c.b555555555bb55555c
                                ....ccb555ddd5555b13bbc.
                                ....ccd55ddddd555b3335c.
                                .....cdd5ddddddd55b335c.
                                ...c.bddddb555bbbd555c..
                                ...ccdddddb555555bccc...
                                ..cccddddddcc5555bcc....
                                .cdccddddddddbcccbcccc..
                                .cddbdddddddddbbbbc55c..
                                .cdddddddddd55dbbbc5c...
                                .cbddddbbbbd55ddbccc....
                                ..cbdddbbbbd555dccc.....
                                ...cccbbbbbbddd555c.....
                                .....ccccccbd55555c.....
                                ...........cc5555c......
                """),
                img("""
                    ........................
                                ............cc..........
                                ............ccc.........
                                ........cc..ccccccc.....
                                ........ccccc555555cc...
                                ........ccb5555555555c..
                                .....cc..b555555555555c.
                                .....cccb555555ff155555c
                                ......cb55555555ff55d55c
                                ......b5555555555555555c
                                ...cc.b555dd5555bb13bbc.
                                ...cccd55ddddd555b3335c.
                                ....ccdd5ddddddd55b335c.
                                .....bddddb55bdddd5555c.
                                ..cccdddddb55bbbbbcccc..
                                .ccccddddddb5555cbcccc..
                                .cdccdddddddc555cbc55c..
                                .cdddddddddddcccbbc5c...
                                .cbddddddd55dbbbbccc....
                                .ccbdddddd555dbbbcbc....
                                ..cccddbbbd555bbccc.....
                                ....ccbbbbbd555cc.......
                                ......ccccbddddbc.......
                                ..........cd5555dc......
                """)],
            500,
            False)
forever(on_forever3)
